/**
 * scripts/set-headers.mjs
 * ===========================================================================
 * Writes dist/_headers after `vite build`.
 *
 * Purpose (Change Brief Sections 2, 6, 13):
 *   - Staging deploys MUST return `X-Robots-Tag: noindex` on every response.
 *   - Production deploys MUST NOT return that header.
 *
 * How it decides:
 *   - Reads VITE_SITE_ENV (set per-context in Netlify UI, or in local .env).
 *   - "production"  -> empty _headers file (no noindex).
 *   - anything else -> _headers file with noindex + nofollow.
 *
 * Netlify picks up dist/_headers automatically. No extra config required.
 * ===========================================================================
 */

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const distDir = resolve(projectRoot, "dist");
const headersPath = resolve(distDir, "_headers");

function readEnv(name) {
  // Netlify injects env vars directly. Local dev reads from .env manually
  // because this script runs after Vite, outside Vite's env loading.
  if (process.env[name]) return process.env[name];

  const envFile = resolve(projectRoot, ".env");
  if (!existsSync(envFile)) return undefined;

  const lines = readFileSync(envFile, "utf8").split("\n");
  for (const line of lines) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (m && m[1] === name) return m[2].replace(/^["']|["']$/g, "");
  }
  return undefined;
}

const env = readEnv("VITE_SITE_ENV") ?? "development";
const isProduction = env === "production";

if (!existsSync(distDir)) {
  console.error("[set-headers] dist/ not found. Run `vite build` first.");
  process.exit(1);
}

mkdirSync(distDir, { recursive: true });

const body = isProduction
  ? `# dist/_headers
# Generated by scripts/set-headers.mjs
# Environment: ${env}
# Production build — no staging noindex applied.

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*.html
  Cache-Control: public, max-age=0, must-revalidate
`
  : `# dist/_headers
# Generated by scripts/set-headers.mjs
# Environment: ${env}
# STAGING BUILD — search engines must not index this deploy.

/*
  X-Robots-Tag: noindex, nofollow

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/*.html
  Cache-Control: public, max-age=0, must-revalidate
`;

writeFileSync(headersPath, body, "utf8");
console.log(
  `[set-headers] Wrote dist/_headers (VITE_SITE_ENV=${env}, noindex=${!isProduction})`
);
